statTracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('', include('trackerApp.urls')),
    path('trackerApp/', include('trackerApp.urls', namespace = 'tracker')),
    path('admin/', admin.site.urls),
]

trackerApp/urls.py
from django.urls import path
from . import views

app_name = 'trackerApp'
urlpatterns = [
    path('', views.WelcomeView.as_view(), name = 'welcomePage'),
    path('1', views.HomePageView.as_view(), name = 'homePage'),
    path('', views.CreateUserView.as_view(), name = 'createUser')

]

statTracker/models.py
from django.db import models

Class User(Models.model):
    user_profile =
    user_StatsForGameA =
    user_StatsForGameB =
    user_StatsForGameC =
    user_StatsForGameD = 

trackerApp/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    userNameText = models.CharField(max_length=250)
    user = models.OneToOneField(User, on_delete = models.CASCADE, primary_key = True)
    def __str__(self):
        return self.userNameText

class Results(models.Model):
    game = models.CharField(max_length=250, default = 'game title')
    kills = models.IntegerField()
    deaths = models.IntegerField()
    time = datetime.datetime.now()

statTracker/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse


def homePage(request):
    return HttpResponse("This is the home page where you can go to the different places on the site")

def statPage(request, question_id):
    return HttpResponse("You're Looking at your own stats")

def addStats(request, question_id):
    return HttpResponse("You are adding stats to your file")

def otherUsersStats(request, question_id):
    return HttpResponse("You are looking at %s's stats" % username)

trackerApp/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.utils import timezone
from .models import Profile, Results
from django.contrib.auth.models import User

# Create your views here.

class WelcomeView(View):
    def get(self,request):
        template_name = "trackerApp/valoranthomeView.html"
        return render(request, template_name)
    def post(self, request):
        template_name = "trackerApp/welcomePage.html"
        return render(request, template_name)
class HomePageView(View):
    def get(self,request):
        template_name = "trackerApp/loginPage.html"
        return render(request, template_name)
    def post(self, request):
        template_name = "trackerApp/loginPage.html"
        return render(request, template_name)


class ProfileView(View):
    def get(self,request):
        template_name = "trackerApp/addStats.html"
        userNameText = Profile.objects.all();
        context = {
            'userNameText':userNameText
            }
        return render(request, template_name, context)

    def post(self,request):
        if request.POST:
            addStats = Results(
                game = request.POST['game'],
                kills = request.POST['kills'],
                deaths = request.POST['deaths']
            )

            addStats.save()

class CreateUserView(View):
    def get(self,request):
        template_name = "trackerApp/createUser.html"
        return render(request, template_name)


def login(request):
    if request.POST:
        if 'inputUsername' in request.POST.keys():
            user = authenticate(username = request.POST['inputUsername'],
            password = request.POST['inputPassword'])
            if user is not None:
                login(request, user = user)
                redirect ("https://localhost:8000/")
        else:
            redirect ("/")

trackerApp/templates/trackerApp/loginPage.html
<!DOCTYPE html>

<form method="post" action = "{% url 'trackerApp:welcomePage' %}">
  {% csrf_token %}
    <div class  = "form-group">
      <label for = "inputUsername">Username</label>
      <input type = "text" class = "form-control" name = "inputUsername" id = "inputUsername" />
    </div>
    <div class  = "form-group">
      <label for = "inputPassword">Password</label>
      <input type = "password" class = "form-control" name = "inputPassword" id = "inputPassword" />
    </div>
    <button type = "submit" class = "btn btn-danger">Login</button>
    <a href= "{% url 'trackerApp:createUser' %}">Create Account</a>
</form>

trackerApp/templates/trackerApp/profile.html
<!DOCTYPE html>
<html>

  <body>
      {% for profile in userNameText %}
      {{profile.userNameText}}
      {% endfor %}
  </body>

</html>


<label for="kills">kills: </label>
<input id="kills" type="text" name="kills" >
<label for="deaths">deaths: </label>
<input id="deaths" type="text" name="deaths" >
<label for="game">game: </label>
<input id="game" type="text" name="game" >
<input type="submit" value="OK">

trackerApp/templates/trackerApp/siegeHomeView.html
<!DOCTYPE html>
<form method="post">
  {% csrf_token %}
  <html>
  <head>
    {% load static %}
     <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
     <link rel="preconnect" href="https://fonts.gstatic.com">
     <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@700&display=swap" rel="stylesheet">
  </head>
    <body>
      <div class = "navbar">
      </div>


    </body>
  </html>
</form>

trackerApp/templates/trackerApp/valorantHomeView.html
<!DOCTYPE html>
  <html>
  <head>
    {% load static %}
     <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
     <link rel="preconnect" href="https://fonts.gstatic.com">
     <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@700&display=swap" rel="stylesheet">
  </head>
    <body>
      <div class = "valorant-navbar">
        <p class = "valorant-page-title" style = "font-family: 'Noto Sans', sans-serif;"> STAT-TRACKER.COM</p>
        <p class = "valorant-leaderboard-button" style = "font-family: 'Noto Sans', sans-serif;"> LEADERBOARD</p>
        <p class = "valorant-input-button" style = "font-family: 'Noto Sans', sans-serif;"> INPUT STATS</p>
        <p class = "valorant-profile-button" style = "font-family: 'Noto Sans', sans-serif;"> YOUR PROFILE</p>
      </div>



    </body>
  </html>

trackerApp/templates/trackerApp/welcomePage.html
<!DOCTYPE html>
<form method="post">
  {% csrf_token %}
  <html>
  <head>
    {% load static %}
     <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
     <link rel="preconnect" href="https://fonts.gstatic.com">
     <link href="https://fonts.googleapis.com/css2?family=Noto+Sans:wght@700&display=swap" rel="stylesheet">
  </head>
    <body>
      <div class = "navbar">
        <p class = "page-title" style = "font-family: 'Noto Sans', sans-serif;"> STAT-TRACKER.COM </p>
        <p class = "page-subtitle" style = "font-family: 'Noto Sans', sans-serif;"> CHOSE A GAME BELOW TO BEGIN </p>
        <a href = "{% url 'trackerApp:homePage' %}"><div class = "siege-button"> <p class = "valorant-subtitle" style = "font-family: 'Noto Sans', sans-serif;"> VALORANT </p></div></a>
        <div class = "valorant-button"></div>
        <div class = "fortnite-button"></div>




        <p class = "siege-subtitle" style = "font-family: 'Noto Sans', sans-serif;"> R6:SIEGE </p>
        <p class = "fortnite-subtitle" style = "font-family: 'Noto Sans', sans-serif;"> FORTNITE </p>
      </div>


    </body>
  </html>
</form>